baseURL = '/'
languageCode = 'en-US'
title = 'Revanth Gundala'
enableRobotsTXT = true
enableEmoji = true
summaryLength = 20

[markup]
  [markup.highlight]
    codeFences = true
    style = 'dracula'
  [markup.goldmark.renderer]
    unsafe = true